const defaultProducts=[
{id:1,name:"Wireless Bluetooth Earbuds",price:1499,cost:850,stock:20,cat:"Audio",icon:"🎧",discount:15},
{id:2,name:"Fast Charger 33W",price:899,cost:500,stock:35,cat:"Power",icon:"🔌",discount:10},
{id:3,name:"20,000mAh Power Bank",price:1999,cost:1250,stock:18,cat:"Power",icon:"🔋",discount:20},
{id:4,name:"Type-C Fast Charging Cable",price:499,cost:250,stock:60,cat:"Mobile Accessories",icon:"🔗",discount:5},
{id:5,name:"RGB Gaming Mouse",price:1299,cost:750,stock:15,cat:"Gaming",icon:"🖱️",discount:12},
{id:6,name:"Wireless Game Controller",price:1799,cost:1100,stock:12,cat:"Gaming",icon:"🎮",discount:10},
{id:7,name:"128GB Memory Card",price:999,cost:650,stock:25,cat:"Computer",icon:"💾",discount:8},
{id:8,name:"Adjustable Phone Stand",price:599,cost:300,stock:40,cat:"Mobile Accessories",icon:"📱",discount:10}
];
let products=JSON.parse(localStorage.getItem("as_products")||"null")||defaultProducts;
let cart=JSON.parse(localStorage.getItem("as_cart")||"[]"), activeCat="All";
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("as_products",JSON.stringify(products));localStorage.setItem("as_cart",JSON.stringify(cart))}
function money(n){return "Rs. "+Number(n).toLocaleString()}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function renderCats(){let cats=["All",...new Set(products.map(p=>p.cat))];$("categoryList").innerHTML=cats.map(c=>`<button class="cat ${c===activeCat?"active":""}" onclick="activeCat='${c}';renderAll()">${c}</button>`).join("")}
function renderProducts(){let q=$("search").value.toLowerCase();let list=products.filter(p=>(activeCat==="All"||p.cat===activeCat)&&p.name.toLowerCase().includes(q));$("resultCount").textContent=list.length+" products";$("productGrid").innerHTML=list.map(p=>`<article class="card"><div class="photo">${p.icon||"📦"}</div><div class="info"><div class="tag">${p.cat}</div><div class="name">${p.name}</div><div class="price">${money(p.price)} <span class="old">${money(Math.round(p.price*1.2))}</span></div><div class="stock">${p.stock>0?p.stock+" in stock":"Out of stock"}</div><button class="primary buy" ${p.stock<1?"disabled":""} onclick="addCart(${p.id})">Add to cart</button></div></article>`).join("")||"<p>No matching products.</p>"}
function renderAll(){renderCats();renderProducts();$("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function addCart(id){let p=products.find(x=>x.id===id), item=cart.find(x=>x.id===id);if(!p||p.stock<1)return toast("Out of stock");if(item)item.qty++;else cart.push({id,qty:1});save();renderAll();toast("Added to cart")}
function openCart(){let box=$("cartItems");if(!cart.length)box.innerHTML="<p>Your cart is empty.</p>";else box.innerHTML=cart.map(x=>{let p=products.find(y=>y.id===x.id);return `<div class="cartRow"><span>${p.name}<br><small>${money(p.price)} × ${x.qty}</small></span><span><b>${money(p.price*x.qty)}</b><br><button onclick="changeQty(${x.id},-1)">−</button> <button onclick="changeQty(${x.id},1)">+</button></span></div>`}).join("");let total=cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);$("cartTotal").textContent="Total: "+money(total);$("cartModal").classList.add("show")}
function changeQty(id,d){let x=cart.find(a=>a.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);save();openCart();renderAll()}
function checkout(){if(!cart.length)return toast("Cart is empty");closeModal("cartModal");$("checkoutModal").classList.add("show")}
function placeOrder(e){e.preventDefault();let order={id:"AS"+Date.now().toString().slice(-7),name:$("cName").value,phone:$("cPhone").value,province:$("cProvince").value,city:$("cCity").value,address:$("cAddress").value,payment:$("cPayment").value,items:cart,date:new Date().toLocaleString()};let orders=JSON.parse(localStorage.getItem("as_orders")||"[]");orders.unshift(order);localStorage.setItem("as_orders",JSON.stringify(orders));cart=[];save();closeModal("checkoutModal");$("checkoutForm").reset();renderAll();toast("Order "+order.id+" placed")}
function closeModal(id){$(id).classList.remove("show")}
function openAdmin(){let pass=prompt("Admin password (demo):");if(pass!=="admin123")return toast("Incorrect password");$("adminModal").classList.add("show");adminHome()}
function adminHome(){ $("adminContent").innerHTML=`<h2>⚙️ Admin Dashboard</h2><div class="adminTabs"><button onclick="adminHome()">Products</button><button onclick="adminOrders()">Orders</button><button onclick="adminSettings()">Store Settings</button></div><button class="primary" onclick="adminAdd()">＋ Add product</button><h3>Products</h3><table class="adminTable"><tr><th>Product</th><th>Price</th><th>Cost</th><th>Stock</th><th></th></tr>${products.map(p=>`<tr><td>${p.name}</td><td>${money(p.price)}</td><td>${money(p.cost)}</td><td>${p.stock}</td><td><button onclick="adminEdit(${p.id})">Edit</button> <button class="danger" onclick="adminDelete(${p.id})">Delete</button></td></tr>`).join("")}</table><p><small>Demo password: admin123. Change it in the production backend before publishing.</small></p>`}
function adminAdd(){adminForm(null)}
function adminEdit(id){adminForm(products.find(p=>p.id===id))}
function adminForm(p){p=p||{id:Date.now(),name:"",price:0,cost:0,stock:0,cat:"Mobile Accessories",icon:"📦",discount:0};$("adminContent").innerHTML=`<h2>${p.name?"Edit":"Add"} Product</h2><input id="apName" placeholder="Product name" value="${p.name}"><input id="apPrice" type="number" placeholder="Selling price" value="${p.price}"><input id="apCost" type="number" placeholder="Cost price" value="${p.cost}"><input id="apStock" type="number" placeholder="Stock" value="${p.stock}"><input id="apCat" placeholder="Category" value="${p.cat}"><input id="apIcon" placeholder="Emoji/icon" value="${p.icon||"📦"}"><input id="apDisc" type="number" placeholder="Discount %" value="${p.discount||0}"><button class="primary" onclick='saveProduct(${p.id})'>Save product</button> <button onclick="adminHome()">Cancel</button>`}
function saveProduct(id){let p=products.find(x=>x.id===id);let data={id,name:$("apName").value,price:+$("apPrice").value,cost:+$("apCost").value,stock:+$("apStock").value,cat:$("apCat").value||"Other",icon:$("apIcon").value||"📦",discount:+$("apDisc").value||0};if(p)Object.assign(p,data);else products.push(data);save();renderAll();adminHome();toast("Product saved")}
function adminDelete(id){if(confirm("Delete this product?")){products=products.filter(p=>p.id!==id);save();renderAll();adminHome()}}
function adminOrders(){let orders=JSON.parse(localStorage.getItem("as_orders")||"[]");$("adminContent").innerHTML=`<h2>📦 Orders</h2><div class="adminTabs"><button onclick="adminHome()">Products</button><button onclick="adminOrders()">Orders</button><button onclick="adminSettings()">Store Settings</button></div>${orders.length?orders.map(o=>`<div style="border:1px solid #eee;padding:12px;border-radius:10px;margin:8px 0"><b>${o.id}</b> • ${o.date}<br>${o.name} • ${o.phone}<br>${o.city}, ${o.province} • ${o.payment}<br>${o.items.map(i=>{let p=products.find(x=>x.id===i.id);return p?p.name+" × "+i.qty:"Deleted product"}).join(", ")}</div>`).join(""):"<p>No orders yet.</p>"}`}
function adminSettings(){let s=JSON.parse(localStorage.getItem("as_settings")||"{}");$("adminContent").innerHTML=`<h2>🏪 Store Settings</h2><div class="adminTabs"><button onclick="adminHome()">Products</button><button onclick="adminOrders()">Orders</button><button onclick="adminSettings()">Store Settings</button></div><input id="stPhone" placeholder="Phone" value="${s.phone||"+977-98XXXXXXXX"}"><input id="stEmail" placeholder="Email" value="${s.email||"anurajstore@example.com"}"><input id="stAddress" placeholder="Address" value="${s.address||"Kathmandu, Nepal"}"><input id="stDelivery" placeholder="Delivery policy" value="${s.delivery||"Delivery across Nepal"}"><button class="primary" onclick="saveSettings()">Save settings</button><p><small>eSewa/Khalti require your merchant credentials and a server-side payment integration. Do not put secret keys in this HTML/JS.</small></p>`}
function saveSettings(){localStorage.setItem("as_settings",JSON.stringify({phone:$("stPhone").value,email:$("stEmail").value,address:$("stAddress").value,delivery:$("stDelivery").value}));toast("Settings saved")}
renderAll();